import type { FeatureOntologyEntry } from '@dealghost/shared'
import { prisma } from '../db/prisma.js'

// ── 68 canonical features across 18 categories ──────────────────────────────
// Structured as a capability graph: description + relatedFeatures + commonProjectTypes
// enable semantic matching, discovery suggestions, and future domain-based filtering.

export const ONTOLOGY_SEED: FeatureOntologyEntry[] = [
  // ── AUTH ──────────────────────────────────────────────────────────────────
  {
    id: 'user_auth',
    canonicalName: 'User Authentication',
    category: 'auth',
    description: 'Core account creation and session management — the foundation of any user-facing application.',
    aliases: ['login', 'sign in', 'sign up', 'register', 'authentication', 'user accounts', 'account system'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 16,
    typicalHoursMax: 32,
    dependencies: [],
    incompatibleWith: [],
    relatedFeatures: ['oauth_social_login', 'role_based_access_control', 'user_profiles'],
    commonProjectTypes: ['saas_platform', 'marketplace', 'delivery_app', 'booking_platform', 'ecommerce_store', 'social_platform'],
  },
  {
    id: 'oauth_social_login',
    canonicalName: 'Social / OAuth Login',
    category: 'auth',
    description: 'Allow users to sign in using existing Google, Apple, or Facebook accounts instead of creating a new password.',
    aliases: ['google login', 'facebook login', 'apple login', 'social login', 'oauth', 'sso via social', 'sign in with google'],
    typicalComplexity: 'LOW',
    typicalHoursMin: 8,
    typicalHoursMax: 16,
    dependencies: ['user_auth'],
    incompatibleWith: [],
    relatedFeatures: ['user_auth', 'user_profiles'],
    commonProjectTypes: ['saas_platform', 'marketplace', 'social_platform', 'mobile_app'],
  },
  {
    id: 'two_factor_auth',
    canonicalName: 'Two-Factor Authentication',
    category: 'auth',
    description: 'Add a second verification step (OTP via SMS/email or authenticator app) to protect user accounts.',
    aliases: ['2fa', 'mfa', 'two factor', 'multi factor auth', 'otp', 'authenticator app', 'sms verification'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 12,
    typicalHoursMax: 24,
    dependencies: ['user_auth'],
    incompatibleWith: [],
    relatedFeatures: ['user_auth', 'sms_notifications'],
    commonProjectTypes: ['fintech_app', 'saas_platform', 'healthcare_app'],
  },
  {
    id: 'role_based_access_control',
    canonicalName: 'Role-Based Access Control',
    category: 'auth',
    description: 'Define what different user types (admin, manager, customer) can see and do within the system.',
    aliases: ['rbac', 'user roles', 'permissions', 'admin vs user', 'access levels', 'user groups', 'authorization'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 20,
    typicalHoursMax: 40,
    dependencies: ['user_auth'],
    incompatibleWith: [],
    relatedFeatures: ['admin_panel', 'audit_trail'],
    commonProjectTypes: ['saas_platform', 'marketplace', 'logistics_platform', 'dashboard_tool'],
  },
  {
    id: 'single_sign_on',
    canonicalName: 'Single Sign-On (SSO)',
    category: 'auth',
    description: 'Enterprise-grade login where employees use their corporate identity provider (Okta, Azure AD) to access the app.',
    aliases: ['sso', 'saml', 'enterprise login', 'okta', 'active directory', 'ldap', 'corporate login'],
    typicalComplexity: 'HIGH',
    typicalHoursMin: 24,
    typicalHoursMax: 48,
    dependencies: ['user_auth'],
    incompatibleWith: [],
    relatedFeatures: ['role_based_access_control'],
    commonProjectTypes: ['saas_platform', 'dashboard_tool'],
  },
  {
    id: 'passwordless_auth',
    canonicalName: 'Passwordless Authentication',
    category: 'auth',
    description: 'Login via a magic link sent to email or a passkey — no password required.',
    aliases: ['magic link', 'email link login', 'passkey', 'webauthn', 'no password'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 12,
    typicalHoursMax: 24,
    dependencies: ['user_auth'],
    incompatibleWith: [],
    relatedFeatures: ['user_auth', 'email_notifications'],
    commonProjectTypes: ['saas_platform', 'mobile_app'],
  },

  // ── PAYMENTS ──────────────────────────────────────────────────────────────
  {
    id: 'payment_processing',
    canonicalName: 'Payment Processing',
    category: 'payments',
    description: 'Accept card and digital wallet payments online via Stripe, Braintree, or similar gateway.',
    aliases: ['stripe', 'payments', 'pay online', 'checkout', 'credit card', 'card payments', 'accept payments', 'online payments'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 24,
    typicalHoursMax: 48,
    dependencies: ['user_auth'],
    incompatibleWith: [],
    relatedFeatures: ['invoice_generation', 'subscription_billing', 'order_management'],
    commonProjectTypes: ['ecommerce_store', 'marketplace', 'delivery_app', 'booking_platform', 'saas_platform'],
  },
  {
    id: 'subscription_billing',
    canonicalName: 'Subscription Billing',
    category: 'payments',
    description: 'Charge customers on a recurring basis (monthly/annual) with plan management and automatic renewal.',
    aliases: ['subscriptions', 'recurring billing', 'monthly plan', 'saas billing', 'stripe subscriptions', 'billing plans', 'recurring payments'],
    typicalComplexity: 'HIGH',
    typicalHoursMin: 32,
    typicalHoursMax: 64,
    dependencies: ['payment_processing'],
    incompatibleWith: [],
    relatedFeatures: ['subscription_management', 'invoice_generation'],
    commonProjectTypes: ['saas_platform', 'content_platform', 'education_platform'],
  },
  {
    id: 'invoice_generation',
    canonicalName: 'Invoice Generation',
    category: 'payments',
    description: 'Automatically generate and send PDF invoices or receipts to customers after transactions.',
    aliases: ['invoices', 'pdf invoices', 'billing history', 'receipts', 'invoice download'],
    typicalComplexity: 'LOW',
    typicalHoursMin: 8,
    typicalHoursMax: 20,
    dependencies: ['payment_processing'],
    incompatibleWith: [],
    relatedFeatures: ['payment_processing', 'order_management', 'reporting_system'],
    commonProjectTypes: ['saas_platform', 'marketplace', 'logistics_platform'],
  },
  {
    id: 'escrow_payments',
    canonicalName: 'Escrow / Held Payments',
    category: 'payments',
    description: 'Hold funds securely until a condition is met (job completed, item delivered) then release to the recipient.',
    aliases: ['escrow', 'hold funds', 'release payment', 'milestone payment', 'secure payment hold'],
    typicalComplexity: 'HIGH',
    typicalHoursMin: 40,
    typicalHoursMax: 80,
    dependencies: ['payment_processing'],
    incompatibleWith: [],
    relatedFeatures: ['commission_management', 'dispute_resolution'],
    commonProjectTypes: ['marketplace', 'service_marketplace', 'real_estate_platform'],
  },
  {
    id: 'multi_currency',
    canonicalName: 'Multi-Currency Support',
    category: 'payments',
    description: 'Accept and display prices in multiple currencies with automatic conversion and localised formatting.',
    aliases: ['multiple currencies', 'international payments', 'currency conversion', 'usd eur gbp', 'global payments'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 16,
    typicalHoursMax: 32,
    dependencies: ['payment_processing'],
    incompatibleWith: [],
    relatedFeatures: ['payment_processing'],
    commonProjectTypes: ['marketplace', 'saas_platform', 'ecommerce_store'],
  },
  {
    id: 'commission_management',
    canonicalName: 'Commission / Revenue Split',
    category: 'payments',
    description: 'Automatically split payments between the platform and vendors or service providers at a configured rate.',
    aliases: ['platform fee', 'take rate', 'commission', 'revenue share', 'vendor payout', 'split payment'],
    typicalComplexity: 'HIGH',
    typicalHoursMin: 32,
    typicalHoursMax: 60,
    dependencies: ['payment_processing', 'escrow_payments'],
    incompatibleWith: [],
    relatedFeatures: ['vendor_dashboard', 'reporting_system'],
    commonProjectTypes: ['marketplace', 'service_marketplace', 'delivery_app'],
  },

  // ── TRACKING ──────────────────────────────────────────────────────────────
  {
    id: 'realtime_delivery_tracking',
    canonicalName: 'Real-time Delivery Tracking',
    category: 'tracking',
    description: 'Track moving delivery agents or orders in real time on a map with live location updates pushed to the customer.',
    aliases: ['live tracking', 'gps tracking', 'track driver', 'delivery tracking', 'order tracking', 'track my order', 'live location', 'driver location'],
    typicalComplexity: 'HIGH',
    typicalHoursMin: 40,
    typicalHoursMax: 80,
    dependencies: ['maps_integration', 'websocket_realtime'],
    incompatibleWith: [],
    relatedFeatures: ['push_notifications', 'order_management', 'route_optimization'],
    commonProjectTypes: ['delivery_app', 'marketplace', 'logistics_platform'],
  },
  {
    id: 'order_status_tracking',
    canonicalName: 'Order Status Tracking',
    category: 'tracking',
    description: 'Let customers follow their order through discrete status stages: placed → confirmed → dispatched → delivered.',
    aliases: ['order status', 'track order', 'shipment tracking', 'delivery status', 'order updates', 'parcel tracking'],
    typicalComplexity: 'LOW',
    typicalHoursMin: 8,
    typicalHoursMax: 20,
    dependencies: ['order_management'],
    incompatibleWith: [],
    relatedFeatures: ['push_notifications', 'email_notifications', 'order_management'],
    commonProjectTypes: ['ecommerce_store', 'delivery_app', 'marketplace'],
  },
  {
    id: 'asset_tracking',
    canonicalName: 'Asset / Fleet Tracking',
    category: 'tracking',
    description: 'Monitor real-time location and status of physical assets, vehicles, or equipment across a fleet.',
    aliases: ['fleet tracking', 'vehicle tracking', 'asset management', 'equipment tracking', 'iot tracking', 'telematics'],
    typicalComplexity: 'HIGH',
    typicalHoursMin: 60,
    typicalHoursMax: 120,
    dependencies: ['maps_integration', 'websocket_realtime'],
    incompatibleWith: [],
    relatedFeatures: ['analytics_dashboard', 'push_notifications', 'route_optimization'],
    commonProjectTypes: ['logistics_platform', 'delivery_app'],
  },

  // ── NOTIFICATIONS ─────────────────────────────────────────────────────────
  {
    id: 'push_notifications',
    canonicalName: 'Push Notifications',
    category: 'notifications',
    description: "Send alerts directly to a user's mobile device even when the app is closed, via FCM or APNs.",
    aliases: ['push notifications', 'mobile alerts', 'app notifications', 'fcm', 'apns', 'mobile push'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 16,
    typicalHoursMax: 32,
    dependencies: [],
    incompatibleWith: [],
    relatedFeatures: ['in_app_notifications', 'email_notifications'],
    commonProjectTypes: ['delivery_app', 'marketplace', 'social_platform', 'booking_platform', 'mobile_app'],
  },
  {
    id: 'email_notifications',
    canonicalName: 'Email Notifications',
    category: 'notifications',
    description: 'Send automated transactional emails — confirmations, receipts, alerts, and onboarding sequences.',
    aliases: ['email alerts', 'transactional email', 'sendgrid', 'mailgun', 'email system', 'automated emails'],
    typicalComplexity: 'LOW',
    typicalHoursMin: 8,
    typicalHoursMax: 20,
    dependencies: [],
    incompatibleWith: [],
    relatedFeatures: ['push_notifications', 'in_app_notifications'],
    commonProjectTypes: ['saas_platform', 'ecommerce_store', 'marketplace', 'booking_platform'],
  },
  {
    id: 'sms_notifications',
    canonicalName: 'SMS Notifications',
    category: 'notifications',
    description: 'Send automated text messages for time-sensitive alerts — order updates, OTPs, appointment reminders.',
    aliases: ['sms', 'text message', 'twilio', 'sms alerts', 'text alerts', 'whatsapp notifications'],
    typicalComplexity: 'LOW',
    typicalHoursMin: 8,
    typicalHoursMax: 16,
    dependencies: [],
    incompatibleWith: [],
    relatedFeatures: ['push_notifications', 'email_notifications'],
    commonProjectTypes: ['delivery_app', 'booking_platform', 'marketplace'],
  },
  {
    id: 'in_app_notifications',
    canonicalName: 'In-App Notification Center',
    category: 'notifications',
    description: 'A bell icon with a notification feed inside the app showing recent alerts with unread count badge.',
    aliases: ['notification bell', 'notification center', 'in-app alerts', 'notification feed', 'unread count'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 12,
    typicalHoursMax: 24,
    dependencies: [],
    incompatibleWith: [],
    relatedFeatures: ['push_notifications', 'activity_feed'],
    commonProjectTypes: ['saas_platform', 'marketplace', 'social_platform', 'collaboration_tool'],
  },

  // ── DASHBOARD & ADMIN ─────────────────────────────────────────────────────
  {
    id: 'analytics_dashboard',
    canonicalName: 'Analytics Dashboard',
    category: 'dashboard',
    description: 'Visual charts and metrics giving users or admins insight into activity, revenue, and platform performance.',
    aliases: ['dashboard', 'analytics', 'charts', 'graphs', 'metrics', 'reports', 'kpi dashboard', 'data dashboard'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 24,
    typicalHoursMax: 60,
    dependencies: [],
    incompatibleWith: [],
    relatedFeatures: ['reporting_system', 'admin_panel'],
    commonProjectTypes: ['saas_platform', 'marketplace', 'logistics_platform', 'dashboard_tool'],
  },
  {
    id: 'admin_panel',
    canonicalName: 'Admin Panel',
    category: 'dashboard',
    description: 'A secure back-office interface for administrators to manage users, content, orders, and system settings.',
    aliases: ['admin dashboard', 'admin portal', 'management console', 'back office', 'admin area', 'control panel'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 32,
    typicalHoursMax: 60,
    dependencies: ['role_based_access_control'],
    incompatibleWith: [],
    relatedFeatures: ['audit_trail', 'analytics_dashboard', 'user_profiles'],
    commonProjectTypes: ['saas_platform', 'marketplace', 'ecommerce_store', 'delivery_app'],
  },
  {
    id: 'vendor_dashboard',
    canonicalName: 'Vendor / Seller Dashboard',
    category: 'dashboard',
    description: 'A dedicated portal for sellers or service providers to manage their listings, orders, and earnings.',
    aliases: ['vendor portal', 'seller dashboard', 'partner dashboard', 'restaurant dashboard', 'store dashboard'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 24,
    typicalHoursMax: 48,
    dependencies: ['role_based_access_control'],
    incompatibleWith: [],
    relatedFeatures: ['analytics_dashboard', 'commission_management', 'order_management'],
    commonProjectTypes: ['marketplace', 'service_marketplace', 'delivery_app'],
  },
  {
    id: 'reporting_system',
    canonicalName: 'Reporting & Exports',
    category: 'dashboard',
    description: 'Generate, filter, and export structured reports (CSV, PDF) on business activity and KPIs.',
    aliases: ['reports', 'export data', 'csv export', 'pdf reports', 'financial reports', 'download reports'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 16,
    typicalHoursMax: 40,
    dependencies: [],
    incompatibleWith: [],
    relatedFeatures: ['analytics_dashboard', 'bulk_import_export'],
    commonProjectTypes: ['saas_platform', 'logistics_platform', 'dashboard_tool', 'fintech_app'],
  },

  // ── BOOKING ───────────────────────────────────────────────────────────────
  {
    id: 'booking_system',
    canonicalName: 'Booking / Reservation System',
    category: 'booking',
    description: 'Allow users to select a time slot and reserve a service, appointment, or resource with confirmation.',
    aliases: ['booking', 'reservations', 'appointments', 'schedule', 'book a slot', 'time slots', 'booking flow'],
    typicalComplexity: 'HIGH',
    typicalHoursMin: 40,
    typicalHoursMax: 80,
    dependencies: ['user_auth', 'calendar_integration'],
    incompatibleWith: [],
    relatedFeatures: ['availability_management', 'appointment_reminders', 'payment_processing'],
    commonProjectTypes: ['booking_platform', 'service_marketplace', 'healthcare_app', 'education_platform'],
  },
  {
    id: 'calendar_integration',
    canonicalName: 'Calendar Integration',
    category: 'booking',
    description: "Sync bookings with Google Calendar, Outlook, or iCal so events appear in the user's personal calendar.",
    aliases: ['google calendar', 'calendar sync', 'ical', 'outlook calendar', 'calendar events', 'add to calendar'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 16,
    typicalHoursMax: 32,
    dependencies: [],
    incompatibleWith: [],
    relatedFeatures: ['booking_system', 'appointment_reminders'],
    commonProjectTypes: ['booking_platform', 'saas_platform', 'collaboration_tool'],
  },
  {
    id: 'availability_management',
    canonicalName: 'Availability Management',
    category: 'booking',
    description: 'Let service providers configure their working hours, block out dates, and manage booking capacity.',
    aliases: ['availability', 'working hours', 'schedule management', 'time availability', 'open slots', 'busy times'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 20,
    typicalHoursMax: 40,
    dependencies: ['booking_system'],
    incompatibleWith: [],
    relatedFeatures: ['booking_system', 'calendar_integration'],
    commonProjectTypes: ['booking_platform', 'service_marketplace', 'healthcare_app'],
  },
  {
    id: 'appointment_reminders',
    canonicalName: 'Appointment Reminders',
    category: 'booking',
    description: 'Automatically notify attendees before a scheduled appointment via email, SMS, or push notification.',
    aliases: ['reminders', 'booking reminders', 'appointment alerts', 'confirmation emails', 'reminder notifications'],
    typicalComplexity: 'LOW',
    typicalHoursMin: 8,
    typicalHoursMax: 16,
    dependencies: ['booking_system', 'email_notifications'],
    incompatibleWith: [],
    relatedFeatures: ['sms_notifications', 'push_notifications'],
    commonProjectTypes: ['booking_platform', 'healthcare_app', 'service_marketplace'],
  },

  // ── MESSAGING ─────────────────────────────────────────────────────────────
  {
    id: 'in_app_messaging',
    canonicalName: 'In-App Messaging (1-to-1)',
    category: 'messaging',
    description: 'Private real-time direct messaging between users inside the platform.',
    aliases: ['chat', 'direct message', 'dm', 'messaging', 'inbox', 'private messages', 'user to user chat'],
    typicalComplexity: 'HIGH',
    typicalHoursMin: 40,
    typicalHoursMax: 80,
    dependencies: ['user_auth', 'websocket_realtime'],
    incompatibleWith: [],
    relatedFeatures: ['push_notifications', 'presence_indicators'],
    commonProjectTypes: ['marketplace', 'service_marketplace', 'social_platform'],
  },
  {
    id: 'group_messaging',
    canonicalName: 'Group Messaging / Channels',
    category: 'messaging',
    description: 'Chat rooms or channels where multiple users can communicate and share files together.',
    aliases: ['group chat', 'channels', 'slack-like', 'team chat', 'group conversation', 'chat rooms'],
    typicalComplexity: 'HIGH',
    typicalHoursMin: 48,
    typicalHoursMax: 100,
    dependencies: ['in_app_messaging'],
    incompatibleWith: [],
    relatedFeatures: ['presence_indicators', 'file_upload'],
    commonProjectTypes: ['collaboration_tool', 'social_platform', 'education_platform'],
  },
  {
    id: 'live_chat_support',
    canonicalName: 'Live Chat Support Widget',
    category: 'messaging',
    description: 'A customer support widget where visitors can chat with a support agent in real time.',
    aliases: ['live chat', 'support chat', 'customer chat', 'intercom', 'chat widget', 'help chat'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 16,
    typicalHoursMax: 40,
    dependencies: ['websocket_realtime'],
    incompatibleWith: [],
    relatedFeatures: ['in_app_notifications', 'admin_panel'],
    commonProjectTypes: ['saas_platform', 'ecommerce_store', 'marketplace'],
  },

  // ── MAPS & LOCATION ───────────────────────────────────────────────────────
  {
    id: 'maps_integration',
    canonicalName: 'Maps Integration',
    category: 'maps',
    description: 'Embed an interactive map (Google Maps, Mapbox) to display locations, routes, or geographic data.',
    aliases: ['google maps', 'map view', 'mapbox', 'maps', 'interactive map', 'map display', 'location map'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 16,
    typicalHoursMax: 32,
    dependencies: [],
    incompatibleWith: [],
    relatedFeatures: ['geolocation_services', 'address_autocomplete', 'realtime_delivery_tracking'],
    commonProjectTypes: ['delivery_app', 'marketplace', 'real_estate_platform', 'logistics_platform'],
  },
  {
    id: 'geolocation_services',
    canonicalName: 'Geolocation / User Location',
    category: 'maps',
    description: "Detect the user's current GPS location to power nearby search, delivery radius, or location-aware features.",
    aliases: ['user location', 'detect location', 'gps', 'nearby search', 'location detection', 'find me'],
    typicalComplexity: 'LOW',
    typicalHoursMin: 8,
    typicalHoursMax: 16,
    dependencies: [],
    incompatibleWith: [],
    relatedFeatures: ['maps_integration', 'address_autocomplete'],
    commonProjectTypes: ['delivery_app', 'marketplace', 'social_platform', 'mobile_app'],
  },
  {
    id: 'route_optimization',
    canonicalName: 'Route Optimization',
    category: 'maps',
    description: 'Calculate the most efficient delivery route across multiple stops to minimise time and distance.',
    aliases: ['route planning', 'optimal route', 'delivery route', 'navigation', 'directions api', 'multi-stop routing'],
    typicalComplexity: 'HIGH',
    typicalHoursMin: 32,
    typicalHoursMax: 80,
    dependencies: ['maps_integration'],
    incompatibleWith: [],
    relatedFeatures: ['realtime_delivery_tracking', 'asset_tracking'],
    commonProjectTypes: ['delivery_app', 'logistics_platform'],
  },
  {
    id: 'address_autocomplete',
    canonicalName: 'Address Autocomplete',
    category: 'maps',
    description: 'As the user types an address, suggest completions using Google Places API or similar.',
    aliases: ['address search', 'places api', 'address input', 'location search', 'postcode lookup', 'address finder'],
    typicalComplexity: 'LOW',
    typicalHoursMin: 4,
    typicalHoursMax: 12,
    dependencies: [],
    incompatibleWith: [],
    relatedFeatures: ['maps_integration', 'geolocation_services'],
    commonProjectTypes: ['delivery_app', 'ecommerce_store', 'booking_platform', 'real_estate_platform'],
  },

  // ── MEDIA & FILE STORAGE ──────────────────────────────────────────────────
  {
    id: 'file_upload',
    canonicalName: 'File Upload & Storage',
    category: 'media',
    description: 'Allow users to upload files (images, documents, PDFs) to cloud storage such as S3 or Cloudflare R2.',
    aliases: ['file upload', 'image upload', 'upload files', 'cloud storage', 's3', 'attachments', 'document upload'],
    typicalComplexity: 'LOW',
    typicalHoursMin: 8,
    typicalHoursMax: 20,
    dependencies: [],
    incompatibleWith: [],
    relatedFeatures: ['image_optimization', 'document_management'],
    commonProjectTypes: ['saas_platform', 'marketplace', 'collaboration_tool', 'healthcare_app'],
  },
  {
    id: 'image_optimization',
    canonicalName: 'Image Optimization / CDN',
    category: 'media',
    description: 'Automatically resize, compress, and serve images from a CDN for fast loading across all devices.',
    aliases: ['image resizing', 'image compression', 'cdn images', 'cloudinary', 'image delivery', 'lazy load images'],
    typicalComplexity: 'LOW',
    typicalHoursMin: 8,
    typicalHoursMax: 16,
    dependencies: ['file_upload'],
    incompatibleWith: [],
    relatedFeatures: ['file_upload'],
    commonProjectTypes: ['ecommerce_store', 'marketplace', 'social_platform', 'content_platform'],
  },
  {
    id: 'video_streaming',
    canonicalName: 'Video Upload & Streaming',
    category: 'media',
    description: 'Upload, transcode, and stream video content on-demand via HLS or similar protocol.',
    aliases: ['video upload', 'video streaming', 'video content', 'video player', 'vod', 'hls streaming'],
    typicalComplexity: 'HIGH',
    typicalHoursMin: 40,
    typicalHoursMax: 80,
    dependencies: ['file_upload'],
    incompatibleWith: [],
    relatedFeatures: ['file_upload', 'analytics_dashboard'],
    commonProjectTypes: ['education_platform', 'content_platform', 'social_platform'],
  },

  // ── SEARCH ────────────────────────────────────────────────────────────────
  {
    id: 'full_text_search',
    canonicalName: 'Full-Text Search',
    category: 'search',
    description: 'Search across content, products, or users using Elasticsearch, Algolia, or Postgres full-text indexing.',
    aliases: ['search', 'full text search', 'elasticsearch', 'algolia', 'search functionality', 'search bar'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 16,
    typicalHoursMax: 40,
    dependencies: [],
    incompatibleWith: [],
    relatedFeatures: ['filters_and_facets', 'product_catalog'],
    commonProjectTypes: ['ecommerce_store', 'marketplace', 'saas_platform', 'content_platform'],
  },
  {
    id: 'filters_and_facets',
    canonicalName: 'Filters & Faceted Search',
    category: 'search',
    description: 'Let users narrow search results by category, price range, location, rating, and other dynamic attributes.',
    aliases: ['filters', 'filter by', 'facets', 'advanced search', 'sort and filter', 'search filters'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 16,
    typicalHoursMax: 32,
    dependencies: ['full_text_search'],
    incompatibleWith: [],
    relatedFeatures: ['full_text_search', 'product_catalog'],
    commonProjectTypes: ['ecommerce_store', 'marketplace', 'real_estate_platform'],
  },

  // ── ECOMMERCE ─────────────────────────────────────────────────────────────
  {
    id: 'product_catalog',
    canonicalName: 'Product / Listing Catalog',
    category: 'ecommerce',
    description: 'A structured listing of products or services with descriptions, images, pricing, and categories.',
    aliases: ['product listing', 'catalog', 'menu', 'service listing', 'item catalog', 'product page', 'store catalog'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 24,
    typicalHoursMax: 48,
    dependencies: [],
    incompatibleWith: [],
    relatedFeatures: ['shopping_cart', 'inventory_management', 'full_text_search'],
    commonProjectTypes: ['ecommerce_store', 'marketplace', 'delivery_app'],
  },
  {
    id: 'shopping_cart',
    canonicalName: 'Shopping Cart',
    category: 'ecommerce',
    description: 'Allow users to collect items before checkout, with quantity adjustment and subtotal calculation.',
    aliases: ['cart', 'basket', 'add to cart', 'shopping bag', 'order cart'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 16,
    typicalHoursMax: 32,
    dependencies: ['product_catalog'],
    incompatibleWith: [],
    relatedFeatures: ['payment_processing', 'discount_and_promo'],
    commonProjectTypes: ['ecommerce_store', 'marketplace', 'delivery_app'],
  },
  {
    id: 'order_management',
    canonicalName: 'Order Management',
    category: 'ecommerce',
    description: 'Create, track, update, and fulfil orders — including status management, history, and cancellations.',
    aliases: ['orders', 'order history', 'manage orders', 'order fulfilment', 'order processing', 'order list'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 24,
    typicalHoursMax: 48,
    dependencies: ['user_auth'],
    incompatibleWith: [],
    relatedFeatures: ['order_status_tracking', 'invoice_generation', 'push_notifications'],
    commonProjectTypes: ['ecommerce_store', 'delivery_app', 'marketplace', 'logistics_platform'],
  },
  {
    id: 'inventory_management',
    canonicalName: 'Inventory Management',
    category: 'ecommerce',
    description: 'Track stock levels in real time, receive low-stock alerts, and prevent overselling.',
    aliases: ['stock management', 'inventory', 'stock levels', 'track stock', 'out of stock', 'warehouse management'],
    typicalComplexity: 'HIGH',
    typicalHoursMin: 32,
    typicalHoursMax: 64,
    dependencies: ['product_catalog'],
    incompatibleWith: [],
    relatedFeatures: ['order_management', 'reporting_system'],
    commonProjectTypes: ['ecommerce_store', 'marketplace', 'logistics_platform'],
  },
  {
    id: 'discount_and_promo',
    canonicalName: 'Discounts & Promo Codes',
    category: 'ecommerce',
    description: 'Create and apply promo codes, percentage discounts, or limited-time offers at checkout.',
    aliases: ['promo codes', 'discount codes', 'coupons', 'vouchers', 'special offers', 'promotional pricing'],
    typicalComplexity: 'LOW',
    typicalHoursMin: 8,
    typicalHoursMax: 20,
    dependencies: ['payment_processing'],
    incompatibleWith: [],
    relatedFeatures: ['payment_processing', 'shopping_cart'],
    commonProjectTypes: ['ecommerce_store', 'marketplace', 'delivery_app'],
  },

  // ── SOCIAL & COMMUNITY ────────────────────────────────────────────────────
  {
    id: 'user_profiles',
    canonicalName: 'User Profiles',
    category: 'social',
    description: 'Public or private profile pages where users display their information, activity, and preferences.',
    aliases: ['profile page', 'user profile', 'profile editing', 'bio', 'avatar', 'profile photo', 'public profile'],
    typicalComplexity: 'LOW',
    typicalHoursMin: 8,
    typicalHoursMax: 20,
    dependencies: ['user_auth'],
    incompatibleWith: [],
    relatedFeatures: ['ratings_and_reviews', 'activity_feed'],
    commonProjectTypes: ['social_platform', 'marketplace', 'service_marketplace'],
  },
  {
    id: 'ratings_and_reviews',
    canonicalName: 'Ratings & Reviews',
    category: 'social',
    description: 'Let users rate and review products, services, or other users with star scores and text feedback.',
    aliases: ['reviews', 'ratings', 'star rating', 'user reviews', 'product reviews', 'feedback', 'testimonials'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 16,
    typicalHoursMax: 32,
    dependencies: ['user_auth'],
    incompatibleWith: [],
    relatedFeatures: ['user_profiles', 'order_management'],
    commonProjectTypes: ['marketplace', 'delivery_app', 'service_marketplace', 'booking_platform'],
  },
  {
    id: 'activity_feed',
    canonicalName: 'Activity Feed / Timeline',
    category: 'social',
    description: 'A chronological or ranked feed of user actions, posts, or events visible to the community.',
    aliases: ['feed', 'news feed', 'activity stream', 'timeline', 'social feed', 'updates feed'],
    typicalComplexity: 'HIGH',
    typicalHoursMin: 32,
    typicalHoursMax: 64,
    dependencies: ['user_auth'],
    incompatibleWith: [],
    relatedFeatures: ['push_notifications', 'in_app_notifications', 'user_profiles'],
    commonProjectTypes: ['social_platform', 'collaboration_tool', 'marketplace'],
  },

  // ── REALTIME ──────────────────────────────────────────────────────────────
  {
    id: 'websocket_realtime',
    canonicalName: 'WebSocket / Real-time Updates',
    category: 'realtime',
    description: 'Persistent two-way connection enabling instant server-to-client data push without polling.',
    aliases: ['realtime', 'websockets', 'live updates', 'real-time', 'socket.io', 'live data', 'instant updates'],
    typicalComplexity: 'HIGH',
    typicalHoursMin: 24,
    typicalHoursMax: 48,
    dependencies: [],
    incompatibleWith: [],
    relatedFeatures: ['in_app_messaging', 'realtime_delivery_tracking', 'presence_indicators'],
    commonProjectTypes: ['delivery_app', 'collaboration_tool', 'saas_platform', 'social_platform'],
  },
  {
    id: 'live_collaboration',
    canonicalName: 'Live Collaboration',
    category: 'realtime',
    description: 'Multiple users can edit or interact with the same document, board, or workspace simultaneously.',
    aliases: ['collaborative editing', 'multiplayer', 'real-time collaboration', 'shared editing', 'google docs style'],
    typicalComplexity: 'HIGH',
    typicalHoursMin: 60,
    typicalHoursMax: 120,
    dependencies: ['websocket_realtime'],
    incompatibleWith: [],
    relatedFeatures: ['presence_indicators', 'in_app_messaging'],
    commonProjectTypes: ['collaboration_tool', 'saas_platform', 'education_platform'],
  },
  {
    id: 'presence_indicators',
    canonicalName: 'Presence / Online Status',
    category: 'realtime',
    description: 'Show which users are currently online, actively viewing, or typing in real time.',
    aliases: ['online status', 'who is online', 'presence', 'typing indicator', 'last seen', 'active users'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 12,
    typicalHoursMax: 24,
    dependencies: ['websocket_realtime'],
    incompatibleWith: [],
    relatedFeatures: ['in_app_messaging', 'live_collaboration'],
    commonProjectTypes: ['collaboration_tool', 'social_platform', 'saas_platform'],
  },

  // ── SUBSCRIPTIONS ─────────────────────────────────────────────────────────
  {
    id: 'subscription_management',
    canonicalName: 'Subscription Plan Management',
    category: 'subscriptions',
    description: 'Manage pricing tiers, upgrades, downgrades, free trials, and cancellations for subscription products.',
    aliases: ['pricing plans', 'plan tiers', 'upgrade downgrade', 'free trial', 'plan management', 'membership plans'],
    typicalComplexity: 'HIGH',
    typicalHoursMin: 32,
    typicalHoursMax: 64,
    dependencies: ['subscription_billing'],
    incompatibleWith: [],
    relatedFeatures: ['subscription_billing', 'analytics_dashboard', 'email_notifications'],
    commonProjectTypes: ['saas_platform', 'content_platform', 'education_platform'],
  },
  {
    id: 'usage_based_billing',
    canonicalName: 'Usage-Based Billing',
    category: 'subscriptions',
    description: 'Meter usage (API calls, storage, seats) and charge accordingly — pay-as-you-go model.',
    aliases: ['metered billing', 'pay per use', 'usage billing', 'consumption billing', 'credits system'],
    typicalComplexity: 'HIGH',
    typicalHoursMin: 40,
    typicalHoursMax: 80,
    dependencies: ['subscription_billing'],
    incompatibleWith: [],
    relatedFeatures: ['analytics_dashboard', 'reporting_system'],
    commonProjectTypes: ['saas_platform', 'fintech_app'],
  },

  // ── API & INTEGRATIONS ────────────────────────────────────────────────────
  {
    id: 'rest_api',
    canonicalName: 'REST API',
    category: 'api',
    description: 'Public or private HTTP API allowing programmatic access to platform data and actions.',
    aliases: ['api', 'rest api', 'public api', 'api endpoints', 'backend api', 'json api'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 16,
    typicalHoursMax: 40,
    dependencies: [],
    incompatibleWith: [],
    relatedFeatures: ['webhooks', 'third_party_integration'],
    commonProjectTypes: ['saas_platform', 'logistics_platform', 'dashboard_tool'],
  },
  {
    id: 'webhooks',
    canonicalName: 'Webhooks',
    category: 'api',
    description: 'Send automated HTTP callbacks to external systems when specific events occur on the platform.',
    aliases: ['webhooks', 'event callbacks', 'http callbacks', 'outbound webhooks', 'event notifications'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 12,
    typicalHoursMax: 24,
    dependencies: ['rest_api'],
    incompatibleWith: [],
    relatedFeatures: ['rest_api', 'third_party_integration'],
    commonProjectTypes: ['saas_platform', 'marketplace', 'logistics_platform'],
  },
  {
    id: 'third_party_integration',
    canonicalName: 'Third-Party API Integration',
    category: 'api',
    description: 'Connect to external services (CRM, ERP, accounting, marketing tools) via their APIs.',
    aliases: ['api integration', 'crm integration', 'erp integration', 'zapier', 'external api', 'third party'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 16,
    typicalHoursMax: 48,
    dependencies: [],
    incompatibleWith: [],
    relatedFeatures: ['rest_api', 'webhooks'],
    commonProjectTypes: ['saas_platform', 'marketplace', 'logistics_platform'],
  },

  // ── DATA ──────────────────────────────────────────────────────────────────
  {
    id: 'bulk_import_export',
    canonicalName: 'Bulk Import / Export',
    category: 'data',
    description: 'Allow users to import data from CSV/Excel files or export records in bulk for offline processing.',
    aliases: ['csv import', 'excel import', 'bulk upload', 'data import', 'export csv', 'batch import'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 16,
    typicalHoursMax: 32,
    dependencies: [],
    incompatibleWith: [],
    relatedFeatures: ['reporting_system', 'admin_panel'],
    commonProjectTypes: ['saas_platform', 'logistics_platform', 'dashboard_tool'],
  },

  // ── COMPLIANCE ────────────────────────────────────────────────────────────
  {
    id: 'gdpr_compliance',
    canonicalName: 'GDPR Compliance',
    category: 'compliance',
    description: 'Tools for data privacy compliance — cookie consent, data export on request, and right-to-erasure workflows.',
    aliases: ['gdpr', 'data privacy', 'cookie consent', 'right to be forgotten', 'data deletion', 'privacy policy'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 20,
    typicalHoursMax: 40,
    dependencies: [],
    incompatibleWith: [],
    relatedFeatures: ['audit_trail', 'user_profiles'],
    commonProjectTypes: ['saas_platform', 'healthcare_app', 'fintech_app', 'marketplace'],
  },
  {
    id: 'audit_trail',
    canonicalName: 'Audit Trail / Activity Log',
    category: 'compliance',
    description: 'Immutable log of all significant user and system actions for compliance auditing and debugging.',
    aliases: ['audit log', 'activity log', 'action history', 'audit trail', 'change log', 'event log'],
    typicalComplexity: 'MEDIUM',
    typicalHoursMin: 12,
    typicalHoursMax: 24,
    dependencies: [],
    incompatibleWith: [],
    relatedFeatures: ['admin_panel', 'role_based_access_control'],
    commonProjectTypes: ['fintech_app', 'healthcare_app', 'saas_platform', 'logistics_platform'],
  },

  // ── MONITORING ────────────────────────────────────────────────────────────
  {
    id: 'error_tracking',
    canonicalName: 'Error Tracking & Monitoring',
    category: 'monitoring',
    description: 'Capture, group, and alert on application errors and crashes in production (Sentry, Datadog).',
    aliases: ['sentry', 'error monitoring', 'crash reporting', 'bug tracking', 'application monitoring', 'alerting'],
    typicalComplexity: 'LOW',
    typicalHoursMin: 4,
    typicalHoursMax: 8,
    dependencies: [],
    incompatibleWith: [],
    relatedFeatures: ['analytics_dashboard'],
    commonProjectTypes: ['saas_platform', 'marketplace', 'delivery_app', 'fintech_app'],
  },
]

// ── Seed script ─────────────────────────────────────────────────────────────

async function seed() {
  console.log(`Seeding ${ONTOLOGY_SEED.length} canonical features...`)

  let inserted = 0

  for (const entry of ONTOLOGY_SEED) {
    await prisma.featureOntology.upsert({
      where: { id: entry.id },
      update: {
        canonicalName: entry.canonicalName,
        category: entry.category,
        description: entry.description,
        aliases: entry.aliases,
        typicalComplexity: entry.typicalComplexity ?? null,
        typicalHoursMin: entry.typicalHoursMin ?? null,
        typicalHoursMax: entry.typicalHoursMax ?? null,
        dependencies: entry.dependencies,
        incompatibleWith: entry.incompatibleWith,
        relatedFeatures: entry.relatedFeatures,
        commonProjectTypes: entry.commonProjectTypes,
      },
      create: {
        id: entry.id,
        canonicalName: entry.canonicalName,
        category: entry.category,
        description: entry.description,
        aliases: entry.aliases,
        typicalComplexity: entry.typicalComplexity ?? null,
        typicalHoursMin: entry.typicalHoursMin ?? null,
        typicalHoursMax: entry.typicalHoursMax ?? null,
        dependencies: entry.dependencies,
        incompatibleWith: entry.incompatibleWith,
        relatedFeatures: entry.relatedFeatures,
        commonProjectTypes: entry.commonProjectTypes,
      },
    })
    inserted++
  }

  console.log(`✅ Seeded: ${inserted} features`)
  await prisma.$disconnect()
}

seed().catch((e) => {
  console.error('Seed failed:', e)
  prisma.$disconnect()
  process.exit(1)
})
